### ISSUE TITLE
User Exists Method

### ISSUE THREAD

**Issue by jolhoeft** [jolhoeft/websession.rs#27]
We lack an easy way to check if a user exists. We can get a list of users, but that won't scale well.

**Comment by therealbstern** [comment]
Implemented and published.

**Comment by jolhoeft** [comment]
Odly, Crates.io is reporting 0.5 as the current version

**Comment by jolhoeft** [comment]
I see the new export method, but not a way to check if a username exists.

**Comment by therealbstern** [comment]
Argh.  Fixed in 664217659a97bf5ff96f4fd7cc58462109390b4a but not pushed.

**Comment by therealbstern** [comment]
By which I actually mean 70f84ce20d2e433b4e6de8c20b1d4f1e54a9af02, especially around https://github.com/jolhoeft/websession.rs/commit/70f84ce20d2e433b4e6de8c20b1d4f1e54a9af02#diff-52e19c7832891c3b76fcdc7e21417401R316 and https://github.com/jolhoeft/websession.rs/commit/70f84ce20d2e433b4e6de8c20b1d4f1e54a9af02#diff-52e19c7832891c3b76fcdc7e21417401R470 and https://github.com/jolhoeft/websession.rs/commit/70f84ce20d2e433b4e6de8c20b1d4f1e54a9af02#diff-b4aea3e418ccdb71239b96952d9cddb6R255
