### ISSUE TITLE
Become an OAuth consumer

### ISSUE THREAD

**Issue by therealbstern** [jolhoeft/websession.rs#28]
This eliminates much of the need for end users to make new accounts.

**Comment by therealbstern** [comment]
See the `oauth2` crate.  It's a winner.

**Comment by therealbstern** [comment]
... I'm not convinced this is the right place for this.  It's actually higher level than session management.

**Comment by jolhoeft** [comment]
How would  we connect a session to a particular Oauh login?

**Comment by therealbstern** [comment]
The protocol involves redirecting the user to an external site that than returns them to us with specific parameters (indicating success/failure).  We can tie the response to their cookie then.

**Comment by therealbstern** [comment]
This needs an Authenticator implemented by the owning App, so that it can handle the interactions well.

**Comment by jolhoeft** [comment]
I think OAuth is beyond the scope of websession. It involves a lot of back and forth with the provider, and customer data processing of the providers identity blob. I think that has to be handled application side.
